# Generated by Django 4.2.4 on 2023-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('image', models.ImageField(upload_to='post_image/', verbose_name='фото поста')),
                ('created', models.DateTimeField(verbose_name='Дата пупликации поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
