# Generated by Django 4.2.4 on 2023-08-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_created_profileuser_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'Профиль Пользователя', 'verbose_name_plural': 'Профиль Пользователей'},
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='post.profileuser', verbose_name='Пользователь'),
        ),
    ]
