# Generated by Django 4.2.4 on 2023-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.ImageField(default='static/нет фотографии.png', upload_to='users/profile_image/', verbose_name='аватарка'),
        ),
    ]
